version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
  AfterInstall:
    - location: scripts/install.sh
  ApplicationStart:
    - location: scripts/start_server.sh
